version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - graphdb
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - ./data/db:/var/lib/postgresql/data

  graphdb:
    image: neo4j:latest
    volumes:
      - ./data/graphdb:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
